version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: collabtask-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: collabtask_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - collabtask-network

  redis:
    image: redis:7-alpine
    container_name: collabtask-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - collabtask-network

volumes:
  postgres_data:
  redis_data:

networks:
  collabtask-network:
    driver: bridge 